version: "3.1"

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
